wip

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -368,7 +368,7 @@ usage() {
 	echo "		                   (not recommended)" >&2
 }
 
-options="$(getopt -o hr:s:c:v:j:t:n:o:d -l "help,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
+options="$(getopt -o hr:s:c:v:j:t:n:o:d -l "help,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,debug,,cache:,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
 
 eval set -- "$options"
 
@@ -424,6 +424,11 @@ while [[ $# -gt 0 ]]; do
 		DEBUG=1
 		set -o xtrace
 		;;
+	--cache)
+		CACHEACTION="$2"
+		shift
+		echo "CACHEACTION=$CACHEACTION"
+		;;
 	--skip-cleanup)
 		echo "Skipping cleanup"
 		SKIPCLEANUP=1
@@ -441,11 +446,26 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
-if [[ ${#PATCH_LIST[@]} -eq 0 ]]; then
+if [[ -n "$CACHEACTION" ]]; then
+	if [[ "$CACHEACTION" != "build" ]] && \
+	   [[ "$CACHEACTION" != "copy" ]] ; then
+		warn "unrecognized --cache option: $CACHEACTION"
+		usage
+		exit 1
+	fi
+fi
+
+# verify input patch(es) unless the user is building the kpatch cache
+if [[ ${#PATCH_LIST[@]} -eq 0 ]] && [[ "$CACHEACTION" == "build" ]]; then
 	warn "no patch file(s) specified"
 	usage
 	exit 1
+elif [[ ${#PATCH_LIST[@]} -ne 0 ]] && [[ "$CACHEACTION" == "build" ]]; then
+	warn "--cache $CACHEACTION is not compatible with input .patch files"
+	usage
+	exit 1
 fi
+
 
 # ensure cachedir and tempdir are setup properly and cleaned
 mkdir -p "$TEMPDIR" || die "Couldn't create $TEMPDIR"
@@ -510,6 +530,8 @@ if [[ -n "$USERSRCDIR" ]]; then
 elif [[ -e "$SRCDIR"/.config ]] && [[ -e "$VERSIONFILE" ]] && [[ "$(cat "$VERSIONFILE")" = "$ARCHVERSION" ]]; then
 	echo "Using cache at $SRCDIR"
 
+elif [[ "$CACHEACTION" == "copy" ]] ; then
+	echo "CACHEACTION = $CACHEACTION"
 else
 	if [[ "$DISTRO" = fedora ]] || [[ "$DISTRO" = rhel ]] || [[ "$DISTRO" = ol ]] || [[ "$DISTRO" = centos ]]; then
 
@@ -626,12 +648,18 @@ fi
 # unsupported kernel option checking: CONFIG_DEBUG_INFO_SPLIT
 grep -q "CONFIG_DEBUG_INFO_SPLIT=y" "$CONFIGFILE" && die "kernel option 'CONFIG_DEBUG_INFO_SPLIT' not supported"
 
-echo "Testing patch file(s)"
-cd "$SRCDIR" || die
-apply_patches
-remove_patches
+if [[ "$CACHEACTION" == "copy" ]] ; then
+	echo "Copying original kernel build ${CACHEDIR}.copy -> $CACHEDIR"
+	# cp -r "${CACHEDIR}.copy" "$CACHEDIR"
+	rsync --verbose --archive --delete "${CACHEDIR}.copy/" "$CACHEDIR/"
+fi
 
-cp -LR "$DATADIR/patch" "$TEMPDIR" || die
+if [[ ${#PATCH_LIST[@]} -ne 0 ]] ; then
+	echo "Testing patch file(s)"
+	cd "$SRCDIR" || die
+	apply_patches
+	remove_patches
+fi
 
 if [[ "$ARCH" = "ppc64le" ]]; then
 	ARCH_KCFLAGS="-mcmodel=large"
@@ -642,14 +670,23 @@ export KCFLAGS="-I$DATADIR/patch -ffunction-sections -fdata-sections $ARCH_KCFLA
 echo "Reading special section data"
 find_special_section_data
 
-echo "Building original kernel"
-./scripts/setlocalversion --save-scmversion || die
-make mrproper >> "$LOGFILE" 2>&1 || die
-cp -f "$CONFIGFILE" "$SRCDIR/.config"
-unset KPATCH_GCC_TEMPDIR
-# $TARGETS used as list, no quotes.
-# shellcheck disable=SC2086
-CROSS_COMPILE="$TOOLSDIR/kpatch-gcc " make "-j$CPUS" $TARGETS >> "$LOGFILE" 2>&1 || die
+if [[ "$CACHEACTION" != "copy" ]] ; then
+	echo "Building original kernel"
+	cd "$SRCDIR" || die
+	./scripts/setlocalversion --save-scmversion || die
+	make mrproper >> "$LOGFILE" 2>&1 || die
+	cp -f "$CONFIGFILE" "$SRCDIR/.config"
+	unset KPATCH_GCC_TEMPDIR
+	# $TARGETS used as list, no quotes.
+	# shellcheck disable=SC2086
+	CROSS_COMPILE="$TOOLSDIR/kpatch-gcc " make "-j$CPUS" $TARGETS >> "$LOGFILE" 2>&1 || die
+fi
+
+if [[ "$CACHEACTION" == "build" ]] ; then
+	echo "Original kernel build in $CACHEDIR is complete"
+	exit 0
+fi
+
 
 echo "Building patched kernel"
 apply_patches
@@ -773,6 +810,7 @@ if [[ ! -z "$UBUNTU_KERNEL" ]]; then
 	echo "#define UTS_UBUNTU_RELEASE_ABI $UBUNTU_ABI" >> "$SRCDIR"/include/generated/utsrelease.h
 fi
 
+cp -LR "$DATADIR/patch" "$TEMPDIR" || die
 cd "$TEMPDIR/output" || die
 # $KPATCH_LDFLAGS and result of find used as list, no quotes.
 # shellcheck disable=SC2086,SC2046
