WIP: add --klp-convert switch

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -479,12 +479,13 @@ usage() {
 	echo "		                        (can be specified multiple times)" >&2
 	echo "		-e, --oot-module        Enable patching out-of-tree module," >&2
 	echo "		                        specify current version of module" >&2
+	echo "		--klp-convert           Use klp-convert script" >&2
 	echo "		--skip-cleanup          Skip post-build cleanup" >&2
 	echo "		--skip-compiler-check   Skip compiler version matching check" >&2
 	echo "		                        (not recommended)" >&2
 }
 
-options="$(getopt -o ha:r:s:c:v:j:t:n:o:de: -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,oot-module:,debug,skip-gcc-check,skip-compiler-check,skip-cleanup" -- "$@")" || die "getopt failed"
+options="$(getopt -o ha:r:s:c:v:j:t:n:o:de: -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,oot-module:,debug,klp-convert,skip-gcc-check,skip-compiler-check,skip-cleanup" -- "$@")" || die "getopt failed"
 
 eval set -- "$options"
 
@@ -546,6 +547,10 @@ while [[ $# -gt 0 ]]; do
 		[[ ! -f "$2" ]] && die "out-of-tree module '$2' not found"
 		OOT_MODULE="$(readlink -f "$2")"
 		shift
+		;;
+	--klp-convert)
+		echo "Using klp-convert"
+		KLP_CONVERT=1
 		;;
 	--skip-cleanup)
 		echo "Skipping cleanup"
@@ -1022,6 +1027,11 @@ for i in $FILES; do
 			sed -ri 's/\s+\[<localentry>: 8\]//' "$SYMTAB"
 		fi
 
+
+		if [[ "$KLP_CONVERT" -eq 1 ]]; then
+			CDO_FLAGS+=" --no-klp-relocations"
+		fi
+
 		# create-diff-object orig.o patched.o parent-name parent-symtab
 		#		     Module.symvers patch-mod-name output.o
 		"$TOOLSDIR"/create-diff-object $CDO_FLAGS "orig/$i" "patched/$i" "$KOBJFILE_NAME" \
@@ -1110,8 +1120,22 @@ if [[ "$USE_KLP" -eq 1 ]]; then
 		extra_flags="--no-klp-arch-sections"
 	fi
 	cp -f "$TEMPDIR/patch/$MODNAME.ko" "$TEMPDIR/patch/tmp.ko" || die
-	"$TOOLSDIR"/create-klp-module $extra_flags "$TEMPDIR/patch/tmp.ko" "$TEMPDIR/patch/$MODNAME.ko" 2>&1 | logger 1
-	check_pipe_status create-klp-module
+	if [[ "$KLP_CONVERT" -eq 0 ]]; then
+		"$TOOLSDIR"/create-klp-module $extra_flags "$TEMPDIR/patch/tmp.ko" "$TEMPDIR/patch/$MODNAME.ko" 2>&1 | logger 1
+		check_pipe_status create-klp-module
+	else
+		extra_flags+=" --no-klp-relocations"
+		"$TOOLSDIR"/create-klp-module $extra_flags "$TEMPDIR/patch/tmp.ko" "$TEMPDIR/patch/${MODNAME}-noklp.ko" 2>&1 | logger 1
+		check_pipe_status create-klp-module
+
+		"$TOOLSDIR"/klp-convert/klp-convert "$SRCDIR"/symbols.klp \
+			"$TEMPDIR/patch/${MODNAME}-noklp.ko" \
+			"$TEMPDIR/patch/${MODNAME}.ko" 2>&1 | logger 1
+		check_pipe_status klp-convert
+		if [[ "$rc" -ne 0 ]]; then
+			die "klp-convert failed"
+		fi
+	fi
 fi
 
 if [[ "$CONFIG_MODVERSIONS" -eq 1 ]]; then
